### ISSUE TITLE
esCliche

### ISSUE THREAD

**Issue by MarianoSalerno** [giulivetere/TP-logico#3]
Deberian pasarle el plotTwist que ya saben que paso en una serie a final de temporada y solamente chequear que todas las palabras pasen en otras series

https://github.com/giulivetere/TP-logico/blob/0affb6e514e9753decd6461a13415812a9a218a2/tp1-logico.pl#L129

**Comment by miguelshevchuk** [comment]
Fijense que el enunciado dice: (no necesariamente la misma serie para cada palabra)

Ustedes estan ligando la variable "OtrasPalabrasClave" afuera del forall, lo que provoca que verifique las palabras solo con los giros de una serie.
